### ISSUE TITLE
problem with example SETTINGS.TXT file

### ISSUE THREAD

**Issue by robinsandfort** [OpenAcousticDevices/White-Papers#2]
When trying to run the 
Using_AudioMoth_GPS_Sync_to_Make_Synchronised_Recordings/SETTINGS.TXT
the audiomoth log file shows an error.
The example brackets in line 1 have to be removed "... Anything before the first opening brace, {, and after the first closing brace, } ...".
Thanks for the great new features by the way!
Cheers,
Robin

**Comment by AlexRogersCS** [comment]
Thanks for pointing this out. Now fixed.
